grate-driver/linux

arch/arm/boot/dts/tegra30-asus-tf201.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, drivers/i2c/i2c-hotplug-gpio.c
@digetx we finally managed to reach grouper state of functionality on Transformer Prime. Works everything except sound and cameras (yet!). You can squash my tree commit with previous and remove wip status. Next commits for sound and camera will be applied as separate commits. Also Ion found issue with hotplug i2c (replug of dock failed), and proposed working patch. I'm asking to incorporate it in grate as well.
=> Add device-tree for ASUS Transformer Prime TF201

arch/arm/boot/dts/Makefile, arch/arm/boot/dts/tegra30-pegatron-chagall.dts
Currently tree is not full, but basic functionality like panel, backlight, touch and emmc work good. This commit is to show that device is in development. With next update we will bring remaining missing functionality.
=> WIP: ARM: tegra: Add device-tree for Pegatron Chagall based tablets

arch/arm/boot/dts/tegra30-pegatron-chagall.dts
Fix some minor misconfiguration in Pegatron Chagall pinmux
Signed-off-by: Raffaele Tranquillini <raffaele.tranquillini@gmail.com>
=> ARM: tegra: chagall pinmux fixes

arch/arm/boot/dts/tegra30-asus-tf201.dts, arch/arm/boot/dts/tegra30-asus-tf300t.dts, arch/arm/boot/dts/tegra30-asus-tf700t.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi
This commit contains changes to fix emmc on all transformers and some cosmetic changes.
=> Asus Transformers eMMC fix

Documentation/devicetree/bindings/i2c/i2c-hotplug-gpio.yaml, Documentation/devicetree/bindings/mfd/asus-ec.yaml, drivers/mfd/asus-ec.c
Yaml I tried to fix. Should be fine. Additionally, we discovered new t30 transformer dock revision.
=> Asus EC yaml fixes and new dock revision

arch/arm/Kconfig, arch/arm/boot/dts/Makefile, arch/arm/boot/dts/tegra30-microsoft-surface-rt-efi.dts, arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts, arch/arm/include/asm/acpi_parking_protocol.h
Still needs some testing. When it is done i will squash commits except one which adds efi dts.
=> Add support for Microsoft Surface RT

.github/workflows/build.yml
This should be making tuxmake builds for each push on master branch.
Each time is generated tagged release which overwrites previous.
This tagged release contains tuxmake archive (zImage, dtbs, vmlinux etc.)
Based on: https://gitlab.com/okias/kernel-simpleci
=> CI: github: deploy

.github/workflows/checkpatch.yml
=> CI: implement checkpatch.pl

.github/workflows/build.yml
Also drop ccache from dependencies and separate them into own block
=> FIXUP: speed-up CI with SCCache (thx Mozilla!)

Documentation/devicetree/bindings/display/panel/panel-simple.yaml, Documentation/devicetree/bindings/misc/asus-dockram.yaml, Documentation/devicetree/bindings/power/supply/cg7153am-battery.yaml, arch/arm/boot/dts/Makefile, arch/arm/boot/dts/tegra30-asus-lvds-display.dtsi, arch/arm/boot/dts/tegra30-asus-nexus7-grouper-common.dtsi, arch/arm/boot/dts/tegra30-asus-tf201.dts, arch/arm/boot/dts/tegra30-asus-tf300t.dts, arch/arm/boot/dts/tegra30-asus-tf300tg.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-pegatron-chagall.dts, drivers/gpu/drm/panel/panel-simple.c, drivers/mfd/asus-ec.c, drivers/power/supply/asus-ec-battery.c, drivers/power/supply/asus-ec-charger.c, drivers/power/supply/cg7153am-battery.c, include/linux/mfd/asus-ec.h
- add TF300TG
- switch to simple panels
- improve asus-ec
- add schema yamls
=> Asus Transformers Updates

.github/workflows/build.yml
=> fixup CI (split vmlinux.xz to save bandwidth)

.github/workflows/build.yml
grate_defconfig + pmos.config (so it builds nightly pmOS kernel)
=> FIXUP: CI: add pmOS-grate kernel configs

Documentation/devicetree/bindings/input/imagis,isa1200.yaml, arch/arm/boot/dts/tegra20-glide.dts, arch/arm/boot/dts/tegra20-p4wifi.dts, drivers/leds/leds-isa1200.c
rename + few fixups for glide, added simple yaml definition...
oneplus used also isa1200, seems it has nice docs to incorporate later: https://searchcode.com/file/260805862/Documentation/devicetree/bindings/misc/isa1200.txt/
=> Isa1200 rename

Documentation/devicetree/bindings/input/imagis,isa1200.yaml, arch/arm/boot/dts/tegra114-dalmore.dts, arch/arm/boot/dts/tegra114-roth.dts, arch/arm/boot/dts/tegra114-tn7.dts, arch/arm/boot/dts/tegra124-jetson-tk1.dts, arch/arm/boot/dts/tegra124-nyan.dtsi, arch/arm/boot/dts/tegra124-venice2.dts, arch/arm/boot/dts/tegra20-acer-a500-picasso.dts, arch/arm/boot/dts/tegra20-asus-tf101.dts, arch/arm/boot/dts/tegra20-glide.dts, arch/arm/boot/dts/tegra20-harmony.dts, arch/arm/boot/dts/tegra20-medcom-wide.dts, arch/arm/boot/dts/tegra20-p4wifi.dts, arch/arm/boot/dts/tegra20-paz00.dts, arch/arm/boot/dts/tegra20-plutux.dts, arch/arm/boot/dts/tegra20-qemu.dts, arch/arm/boot/dts/tegra20-seaboard.dts, arch/arm/boot/dts/tegra20-tamonten.dtsi, arch/arm/boot/dts/tegra20-tec.dts, arch/arm/boot/dts/tegra20-trimslice.dts, arch/arm/boot/dts/tegra20-ventana.dts, arch/arm/boot/dts/tegra30-asus-nexus7-grouper-common.dtsi, arch/arm/boot/dts/tegra30-asus-nexus7-grouper-maxim-pmic.dtsi, arch/arm/boot/dts/tegra30-asus-nexus7-grouper-ti-pmic.dtsi, arch/arm/boot/dts/tegra30-beaver.dts, arch/arm/boot/dts/tegra30-cardhu-a02.dts, arch/arm/boot/dts/tegra30-cardhu-a04.dts, arch/arm/boot/dts/tegra30-cardhu.dtsi
Multiple small nitpicks to reduce warnings printed in dtbs_check
=> dtbs_check fixups

.github/workflows/build.yml, Documentation/devicetree/bindings/sound/nvidia,tegra-audio-rt5631.yaml, arch/arm/boot/dts/tegra20-glide.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dts, arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts, arch/arm/boot/dts/tegra30-pegatron-chagall.dts
- decreases number of warnings
- make CI output for reasonable
=> CI + dtbs fixes

Documentation/devicetree/bindings/display/bridge/lvds-codec.yaml, arch/arm/boot/dts/tegra20-glide.dts, arch/arm/boot/dts/tegra20-p4wifi.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts, arch/arm/boot/dts/tegra30-pegatron-chagall.dts
affected:
- p4wifi
- chagall
- glide
- ms surface
=> Fixups multiple dts + Documentation related stuff

arch/arm/boot/dts/tegra30-asus-tf201.dts, arch/arm/boot/dts/tegra30-asus-tf300t.dts, arch/arm/boot/dts/tegra30-asus-tf300tg.dts, arch/arm/boot/dts/tegra30-asus-tf700t.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi
- add missing backlight regulator (testing with u-boot found this issue);
- fix bt compatible fields and irq type
=> Transformers

Documentation/devicetree/bindings/i2c/i2c-hotplug-gpio.yaml, arch/arm/boot/dts/tegra20-asus-tf101.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-microsoft-surface-rt-efi.dts
=> I2cdock fixes

arch/arm/boot/dts/tegra30-microsoft-surface-rt-efi.dts, arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts, drivers/hid/hid-microsoft.c, sound/soc/tegra/Kconfig, sound/soc/tegra/tegra_asoc_machine.c
- APX tCover support
- Audio Output support
- APX: OPP and thermtrip
- Some pinmux stuff
- HID Sensor hub
- custom panel timings
- tCover 2nd gen `KEY_F23` fix
- cleaned up devicetree
=> ARM: tegra: surface-rt: Added new features

arch/arm/boot/dts/tegra30-asus-lvds-display.dtsi, arch/arm/boot/dts/tegra30-asus-nexus7-grouper-common.dtsi, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-pegatron-chagall.dts
Added lcd ddc and chassis-type nodes
=> Transformer updates

arch/arm/boot/dts/tegra30-pegatron-chagall.dts
minor change in chagall power set according to downstream
=> chagall: fix regulators in dts

arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dts
=>  lenovo dt-schema syntax fixes for max77620

arch/arm/boot/dts/tegra114-asus-tf701t.dts, arch/arm/boot/dts/tegra20-asus-tf101.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-pegatron-chagall.dts
=> Transformers and Chagall patches

arch/arm/boot/dts/tegra20-asus-tf101.dts, arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi, arch/arm/boot/dts/tegra30-pegatron-chagall.dts
Add some FIXME tags and fix up device-tree commits
=> Transformer & Chagall updates
