Documentation/devicetree/bindings/arm/tegra.yaml

Add a binding for the Tegra30-based ASUS Transformer Series tablet devices. This group includes Transformer Prime TF201, Transformer Pad TF300T and Transformer Infinity TF700T.
Signed-off-by: Svyatoslav Ryhel <clamor95@gmail.com>

dt-bindings: ARM: tegra: Add ASUS Transformers

---

arch/arm/boot/dts/Makefile
arch/arm/boot/dts/tegra30-asus-tf201.dts
arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi

This commit might not be merged yet, but is definitely cleaner then TF300T and TF700T device trees. Those transformer trees should be reworked.
If you decide to merge it anyway,  I will push one more patch after testing builds to fix all bugs I could find connected with tree.
Some parts of tf201 dts can be moved to common, but I wasn't 100% certain about their common nature among TFs and proper description of some stuff in split form.

ARM: tegra: Add device-tree for ASUS Transformer Prime TF201

---

arch/arm/boot/dts/Makefile
arch/arm/boot/dts/tegra20-tf101.dts

Add initial working version of device tree for ASUS EeePad Transformer TF101.
Basically just copy Ventana device tree and add WiFi and touchscreen to it.

Add device tree for TF101

---

arch/arm/boot/dts/tegra30-cl2n.dts

External sd card slot finally works!

cl2n: correct syntax errors in dts, revert vmmc/vqmmc swap

---

arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dts

ARM: tegra: Lenovo IdeaTab A2109A: enable charging with closely related smb345 driver, add backlight brightness calibration data, temporarily change volume-up to power-key, as sound does not work anyway

ARM: tegra: Lenovo IdeaTab A2109A: fixed PR

---

arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dts

ARM: tegra: lenovo-a2109a: remove fuelgauge battery node, increase charger usb-current-limit, add wifi/bt module product name based on firmware signature

ARM: tegra: lenovo-a2109a: small fixes

---

arch/arm/boot/dts/tegra30-asus-tf201.dts
arch/arm/boot/dts/tegra30-asus-tf300t.dts
arch/arm/boot/dts/tegra30-asus-tf700t.dts
arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi

Common:
- exclude dc node to common;
- update hog name and remove comment;
- set vio to 1.8v;
- add pmic gpios to fixed regs;
- set pwms in backlight as in downstream;
- update thermal;
TF300T:
- add init hog gpio;
- fix sound routing;
Squash please with propper commits. Thanks!

Asus Transformers update

---

arch/arm/boot/dts/tegra30-asus-tf201.dts
arch/arm/boot/dts/tegra30-asus-tf300t.dts
arch/arm/boot/dts/tegra30-asus-tf700t.dts
arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi

- since emmc needs 3.3v to work anyway. Set DDR52 mode
- gpio keys are splitted into buttons (power, vol up and down) and extcon keys (lid, ac, line out)
- sound card names changes to use common ucm (I'm 100% sure rt5631 is exactly same on all transformers that use it; I'm quite sure wm8903 is same on tf300t, chagall and tf101 but that needs proofs)
- changed labeling backlight from backlight_lvds to simple backlight
- changed regulators labeling. Added pmic hog gpio based on Michal's device tree. Changed fixed regulator approach. Regulator 0 is ac_bat 5v, Regulator 1-4 have pmic grios in, Regulator 5,6 are panel regulators, Regulator 7-10 are other fixed regulators neede for proper work.
Everything except emmc works fine. Tested by me, Max, Ihor and Andy.
P. S. May you add tested by to …

Update Asus Transformers

---

arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi

You may squash it into https://github.com/grate-driver/linux/commit/09d709f4373f370c573fdef86d340b34dc621602#diff-d9a889696b367a484322e3667ee72b5ebd92bae3d9aa9d2595fba7a99c8b3e2a
"lm90 0-004c: temp2 out of range, please check!" 
apperas in dmesg on stress teast on tf201 and tf700t

ARM: tegra: transformer: Add interrupt to temperature sensor node

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts
drivers/i2c/i2c-core-base.c

tCover is connected via HID over I2C.
Sadly the slave address is 0x00 which is reserved as general call address.
The patch allows the I2C driver only to accept 0x00 as valid address if the device is a Surface RT.
`i2c-hotplug-gpio` allows to hotplug the tCovers.
Tested on Surface RT with latest grate-linux kernel.
Plugged in the first cover after boot and changed the covers randomly.
Tested with following covers:
- TypeCover 1.Gen
- TypeCover 2.Gen
- TouchCover 1.Gen
- TouchCover 2.Gen
VendorID and ProductID were read correctly and every cover worked after hotplug.
Added the property: `nvidia,panel`

WIP: ARM: tegra: Support for Surface RT Type/Touch/Power-Cover; Display fix

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts

Sorry for sending so small update, we missed this while testing first PR.
`KEY_LEFTMETA` and `KEY_POWER` had default state 1 in evtest.

WIP: ARM: dts: tegra30-microsoft-surfacert: fix gpio-keys

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts

I couldn't set up dtschema on my host, so i can't check it. Feel free to close PR if it doesn't pass lint check or something like that. As i said in IRC it is not very important. ~~Actually the DT has more important things to do and i'm doing useless stuff.~~ I also don't know where it is documented. I used for reference upstream device-trees.
Before patch:
```
microsoft-surfacert:~$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:	gpio-keys
...
```
After patch:
```
microsoft-surfacert:~$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:	GPIO Buttons
...
```

WIP: ARM: dts: tegra30-microsoft-surfacert: add label for gpio-keys

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt-efi.dts
arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts

added CardDetection and WriteProtect gpio. They are the same pins as for Cardhu
pulling the gpio EE0 Low disconnects all USB devices.
closing the lid triggers a hall effect sensor which will suspend the device after 3seconds.
Same sensor is used in Cardhu and Ouya.
lm-sensor read the correct temperatures
tCover depends on a PMIC regulator and an I2C power up sequence provided by UEFI Firmware.
For APX tCover support further steps are necessary.

WIP: ARM: tegra: Surface RT devicetree update

---

arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi
sound/soc/codecs/rt5631.c

- Fix booting from recovery
- Fix RT5631 registers being out of sync after resuming from suspend
- Fix backlight supply
- Add some missing supplies
- Reduce W1 ramp delay to 20ms
- Choose better regulator names

Asus Transformers fixes 

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt-efi.dts
arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts

Now suspend partially (of course CPU voltage is enabled) works, although this is not enough to get working CPU idle. Device used to hang while suspending before this change.
BTW thanks for the tip.

WIP: ARM: tegra: surface-rt-efi: disable LP2

---

arch/arm/boot/dts/tegra30-asus-tf300t.dts
arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi
arch/arm/boot/dts/tegra30-pegatron-chagall.dts
drivers/power/supply/asus-ec-battery.c
drivers/power/supply/asus-ec-charger.c
drivers/power/supply/cg7153am-battery.c

TRANSFORMERS
- vdd1 regulator is removed as it is not used on transformers
- added 5v_sys reg in usb1 accorging to schematics 
- added max current prop in tf battery driver
- re-grouped tf pinmux (cosmetics, no value changes) and commented wm8903 gpio-cfg
- max battery temp multiplied by 10 since it gave me in log 4.5C not 45C
- blocked power supply event from USB (caused device wakeups when plugged on Max TF700T) - may you add commit msg into battery driver commit msg since it may be important
CHAGALL
- vdd1 regulator is removed as it is not used on chagall
- battery driver was updated and now has power led indication support like in downstream
- added extcon gpio keys group (dock insert detection and lineout detection)
- chagall may be removed from WIP since it is mostly complete now

Update Transformers and Chagall

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts

WiFi asks for correct firmware and works with `linux-firmware-mrvl` installed.
Actual chip is 8797. Bluetooth boots with errors about missing firmware. It wants `helper_uart_3000000.bin` and when using the helper which i found for another chip it asks for `mrvl/uart8897_bt.bin` which is wrong (because of wrong helper?) and which i have not found as well as 8797. Also according to ACPI it has interrupt and some additional GPIO, but there are no those in Linux driver.

WIP: ARM: tegra: surface-rt: add WiFi/BT

---

arch/arm/boot/dts/tegra30-microsoft-surface-rt.dts
drivers/power/supply/Kconfig
drivers/power/supply/Makefile
drivers/power/supply/surface-rt-ec.c

Battery and Charger support for UEFI and APX boot.
use CONFIG_BATTERY_CHARGER_SURFACE_RT to enable support.
Signed-off-by: Jonas Schwöbel <jonasschwoebel@yahoo.de>

ARM: Tegra: Surface RT: Battery and Charger support

---

arch/arm/boot/compressed/Makefile

The merge_fdt_bootargs() function by definition consumes more than 1024
bytes of stack because it has a 1024 byte command line on the stack,
meaning that we always get a warning when building this file:
arch/arm/boot/compressed/atags_to_fdt.c: In function 'merge_fdt_bootargs':
arch/arm/boot/compressed/atags_to_fdt.c:98:1: warning: the frame size of 1032 bytes is larger than 1024 bytes [-Wframe-larger-than=]
However, as this is the decompressor and we know that it has a very shallow
call chain, and we do not actually risk overflowing the kernel stack
at runtime here.
This just shuts up the warning by disabling the warning flag for this
file.
Tested on Nexus 7 2012 builds.
Original Author: Arnd Bergmann <arnd@arndb.de>
Reference: https://lore.kernel.org/lkml/8232115.18ykgQ6J5T@wuerfel/
Cc: …

ARM: atags_to_fdt: don't warn about stack size [already sent to kernel ML]

---

arch/arm/boot/dts/tegra20-acer-a500-picasso.dts

"ak,ak8975" is not recognized by dt-bindings, "ak8975" is deprecated so
let's use supported "asahi-kasei,ak8975"

dt-bindigs: arm: tegra20: Acer A500 Picasso correct al8975 compatible

---

arch/arm/boot/dts/tegra30-asus-nexus7-grouper.dtsi
arch/arm/boot/dts/tegra30-asus-nexus7-tilapia.dtsi

This value is inherited by i2c bus.
Discovered while converting nxp,pn544 yaml bindings.

ARM: tegra: drop clock-frequency for NFC

---

arch/arm/boot/dts/tegra20-asus-tf101.dts
arch/arm/boot/dts/tegra30-asus-tf201.dts
arch/arm/boot/dts/tegra30-asus-tf300t.dts
arch/arm/boot/dts/tegra30-asus-tf300tg.dts
arch/arm/boot/dts/tegra30-asus-tf300tl.dts
arch/arm/boot/dts/tegra30-asus-tf700t.dts
arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi
arch/arm/boot/dts/tegra30-pegatron-chagall.dts
drivers/gpio/gpio-tegra.c
sound/soc/tegra/tegra_asoc_machine.c

- gpio-tegra driver needs a review, if remove of tegra_gpio_irq_set_affinity does not brake anything;
- sound was reworked but it misses key part, headset detection. Asus made dumb stuff, Transformers have hp detect, not headset.
PW2 = low   PX2 = low --- default
PW2 = high  PX2 = low --- headset
PW2 = high  PX2 = high --- headphones
tegra_asoc_machine needs a workarround :( it may work for grouper as well btw.

Update sound routing and convert tegra gpio 

---

drivers/gpu/drm/panel/panel-samsung-cmc6230r.c
drivers/leds/leds-isa1200.c
scripts/Makefile.modpost

Fix compilation errors and fix some methods signatures

Fix Compilation Errors
